version: '3.8'

services:
  pinyin-web:
    image: nginx:alpine
    container_name: pinyin-web
    restart: always
    ports:
      - "1471:80"
    volumes:
      - /root/data/pinyin:/usr/share/nginx/html
    networks:
      - pinyin-net

networks:
  pinyin-net:
    driver: bridge
